# Generated by Django 3.2.4 on 2021-08-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('publish', 'author')},
        ),
    ]
